# Generated by Django 4.2.5 on 2023-09-14 04:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("content", models.TextField()),
                ("create_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("author_id", models.CharField(max_length=50)),
                ("topic", models.CharField(max_length=50)),
                ("views", models.PositiveIntegerField(default=0)),
                ("update_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("content_poster", models.ImageField(null=True, upload_to="posters/")),
            ],
        ),
    ]
